SET search_path TO huracandb_onboard;
INSERT INTO canpacket(channel) VALUES (x'7F0'::int);
INSERT INTO canpacket(channel) VALUES (x'7F1'::int);
INSERT INTO canpacket(channel) VALUES (x'7F2'::int);
INSERT INTO canpacket(channel) VALUES (x'7F3'::int);
INSERT INTO canpacket(channel) VALUES (x'7F4'::int);
INSERT INTO canpacket(channel) VALUES (x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F0'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F1'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F2'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F3'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F4'::int);
INSERT INTO candata (id, data, arrivedat, canpacket_channel) VALUES(default, '123456789AUDFRFG', now()::timestamp, x'7F5'::int);
explain analyze select * from candata where canpacket_channel = (x'7F0'::int);
explain analyze select * from candata where canpacket_channel = (x'7F1'::int);
explain analyze select * from candata where canpacket_channel = (x'7F2'::int);
explain analyze select * from candata where canpacket_channel = (x'7F3'::int);
explain analyze select * from candata where canpacket_channel = (x'7F4'::int);
explain analyze select * from candata where canpacket_channel = (x'7F5'::int);
